server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MuziPH/pluralsight-spring-cloudconfig-watolls.git
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/MuziPH/pluralsight-spring-cloudconfig-watolls-perf.git
              search-paths:
                - 'station*'